### ISSUE TITLE
Accessing the `/api/tests` endpoint causes an Internal Server Error

### ISSUE THREAD

**Issue by Syifaa27** [TegarAditya/fluidiatest-api#1]
### Runtime Version
Bun v1.1.21

### Problem Description
When I tried to access the tests endpoint, it caused a server error with details like this in the developer console. It shows some object cannot be serialized because it is a BigInt.

```bash
<-- GET /api/tests
218 |     }
219 |     this.#preparedHeaders["content-type"] = TEXT_PLAIN;
220 |     return typeof arg === "number" ? this.#newResponse(text, arg, headers) : this.#newResponse(text, arg);
221 |   };
222 |   json = (object, arg, headers) => {
223 |     const body = JSON.stringify(object);
                            ^
TypeError: JSON.stringify cannot serialize BigInt.
      at json (/home/mmj/project/Bun/fluidiatest-api/node_modules/hono/dist/context.js:223:23)

--> GET /api/tests 500 136ms
```

**Comment by TegarAditya** [comment]
I think it's an id record that is auto incremented.

**Comment by TegarAditya** [comment]
6172e07172ca93c80325147b4c27211fc8764c2c solved the issue by converting the id to `Number()`

**Comment by Syifaa27** [comment]
> [6172e07](https://github.com/TegarAditya/fluidiatest-api/commit/6172e07172ca93c80325147b4c27211fc8764c2c) solved the issue by converting the id to `Number()`

Thanks, it worked

**Comment by TegarAditya** [comment]
Okay, i will close the issue
